### ISSUE TITLE
Well done, but...

### ISSUE THREAD

**Issue by rstropek** [rstropek-teaching/battleship-quiz-4ahif-SimonPrimetzhofer#2]
Hi!

Well done. However, your algorithm has two major flaws:

1. You greatly favor vertical ships over horizontal ships.
1. Note that `Math.random` returns a number between 0 (including) and 1 (**excluding**). You algorithm never places a ship in index 9 because `Math.random() * 9` will never be 9.

Both problems would make playing on your battleground much easier because a player can ignore a row/column and knows that nearly all ships are vertical.

Greetings,
Rainer Stropek

**Comment by SimonPrimetzhofer** [comment]
Dear Mr. Stropek!

I uploaded a new version, where I considered your feedback and hopefully it's OK like that.

Greetings,

Simon Primetzhofer

**Comment by rstropek** [comment]
Nice 👍 I especially like your comment about diagonal touching ships. This wasn't my intention but I did not explicitly specify this case. You solution of adding a comment documenting your assumption is a good way to handle such situations.

Greetings,
Rainer Stropek.
